* 리뷰
** 식품
*** 농심 포스틱
    + 가격 ???
    + 시식 후기
      맛있음
      
      
** 가전
*** 샤오미 공기청정기S2    
    + 가격
      20만원
    + 사용기
      AUTO모드에서는 소음이 없음
      하지만 공기 청정 효과역시 거의 없다고 보임
      팬으로 공기를 흡입하고 필터로 걸러서 내보내는 선풍기에 필터를 달아 놓은듯한 구조
      옆에서 밥을 먹었는데 아무런 반응 없음-냄세 재거기능은 없는것 같은
** V App
*** 효정
**** 내용
     트와이스 콘서트 관람후 바로 잠을 자기 전에 연습실에와서 연습하던중 켠 노래연습겸 브이앱
     러블리즈, 보아, 여자친구, 현아...등등의 노래를 불렀다
     브이앱이라서 연습이라기보다 뽐내기가 괭어버렀지만 이런기회가 자주 있었으면 좋겠다.
**** 
=======
* 영어공부
  필요함을 절실하게 느끼면서도 엄두를 내지 못하고 있다.
  공부 또는 일을 하면서 언제나 정보의 갈증을 느끼는 지점에 항상 영어를 마주하게 된다.
  영어를 할줄 안다면 더 성장 할수 있었던 순간들 지금과는 다른 환경이 되어있을수 있었던 가능성의 순간들
  나는 기술과 정보를 원하고 그것들을 얻기 위해서 영어가 필요한것이다.
** 영어 공부계획
   말을 처음 배웠던 경험은 없다. 이미 내기억에선 말을 배운후이기 때문이다.
   아이들이 말을 배우는것을 보면 아이와 소통하기 위해서 아이를 둘러싼 모든것들이 협조를 하고 있다.
   아이의 입에서 아빠라는 말을 엄마라는 말을 듣기위해서 부모들은 열과 성을 다한다.
   지금의 나에서 그런 환경을 바랄 수는 없다.
   가장 걸림돌이 되는것은 나는 말이없다는것이다
   표현을 하지않는것이 습관화 돼어서 생각 자채를 하지 않아버린다.
   무언가 글을쓰고 싶지만 내 안에 생각이라는것이 감상이라는것이 떠오르지 않는다.
   예로 많은사람들은 무언가 주변의 환경에 감상을 가지고 표현을 하는것을 난는 보게 된다.
   하지만 똑같은 환경에서 나는 아무것도 느끼지 못하고 그래서 감상또한 없다.
   인터넷에 보면 저마다 맞건 틀리건 자기 자신을 표현하지 못해 안달난사람들이 가득해보인다.
   실시간 방송에 바로바로피드백을 달거나 게임을 하면서 수많은 이야기를 하는 사람들을보며 나도
   같이 어울리고 싶지만 아무런 생각이 없기때문에 끼어들수 없었다.
   게임을 공부했을때도 만드는 기술을 배우는 것보다 항상 만들것을 찾는일이 어려웠고 해내지 못한체
   시간을 다써버리고 멈추어 버린 일이 항상 일어 났다.
   나는 생각없이 수용하는 수용적인 태도를 가지고 산지가 너무나도 오랜세월이라서 
   이 시스템을 바꾸지 않는다면 영어든 무었이든 나는 앞으로 나갈수 없다고 생각한다.
   그래서 매일 만화그리기와 글쓰기를 하려고 했으나 잘 되지 않았다.
   이런 두서 없이 글쓰기가 도음이 되기를 바라지만 과연
   트래이닝 만으로 잘 되기를 바라고 있을 수 만은 없다 이미 나에게 주어진 시간의 상당부분을 
   소비 하였기 때문에 또 얼마나 시간이 남아있는지 알 수 없으므로 하루하루를 귀하게 사용해야 한다.
   그러기 위해서 내가 해야할 일들을 생각나는데로 적어 본다.
*** 계획하기
    남은 시간동안 더 나은 삶을위해서 해야할 일을 적어본다.
**** 글쓰기
     감상이든 리뷰든 아무말이든 글로써 생각을 정리하고 될수있다면 타인에서 전달할수 있도록 해본다.    
     가장 쉬운면서 가장 어련운 일이라고 생각이된다.
     나의 생각을 가지고 정리해서 이제는 밖으로 분출을 할수 있도록 한다.
     - 리뷰
     - 감상문
**** 만화그리기
     이야기와 연출이 담겨있는 그림을 그리고 완성을 할수있도록 한다.
     - 4컷
     - 1컷
     - 서사       
**** 게임 만들기
     글과 만화의 최종 아웃풋은 게임이어야 한다.
     - cpp
     - c#
     - lisp
**** 영어
     글쓰기를 하건 만화를 그리건 게임을 만들건 더 넓은 세계로 나가기위한 최고의 도구, 기술, 지침서라고 생각한다.
*** 기술에 현혹되지 말자
    그동한 공부할때 시행착오를 격은것중 하나인데 기술에 너무 현혹 되는 경우가 많았다.
<<<<<<< HEAD
    새로운 것에만 눈이가고 기술에만 집착해 버리는경우가 많았다
    그 결과 현제 아무것도 할수 없는 상태로 시간만 지나버리고 말았다
    처음부터 끝가지 완료한 기술이 없다.
*** 커피
    나는 커피를 좋아하긴 했지만(믹스커피) 찾아서 마시지는 않았다.
    회사에 취직하고나서부터 마시기 시작햇는데 맛도 맛이지만 커피를 마셔야지만 쉴수 있기 때문이기도 했다
    그냥 가만히 앉아 쉬기 보다 커피를 마시며 쉬면 커피를 다 마실 때까지라는 시간을 정할수 있기 때문에 그리도 남들도 모두 그러기 때문에 쉬고 싶을때마다 커피를 마시기 시작했고
    습관적으로 마시게 되었다.
    카페인 중독이라기엔 없으면 마시지 않는다는걸로 보아 카페인 중독은 아니지 않나 싶다.
    그러다가 학원을 다니며 아이스 아메리카노를 맛보게 되었는데 더운 여름 맛본 아이스 아메리카노는 나름의 좋은 인상을 받게 되었고 카페에 가게 되면 싸기도하고 또 다른 커피의 경우는 이름이 어렵기 때문에 
    그냥 아이스아메리카노를 마시게 되었고 최근엔 간간편하게 집에서 카누를 먹게 되었다.
    카누는 맛이 없어 아무레도 더이상 먹지 않게 될것 같다.
    그냥 탄 맛이 강제로 함유 된듯한 맛 마치 배달음식의 불맛 같은 진짬뽕의 불맛 기름 같이 불쾌한 맛이다.
    그냥 물로 만족해야 한다.
*** 인스크립티드
    성공한 사업가의 색다른 시선 남들과 같아서는 성공할수 없다는 말들 하지만 막연히 생각해 왔던것들을 정리해주는 내용이라서 구매해버렸다.
    이러한 종류의 책들의 공통점은 결국 누구나 알고 있는것을 글로써 그리고 논리로서 정리를 해주었다는것에 의의를 가져야 할것이다.
    요즈음 매우크게 퇴사욕구를 느끼고 있다.
    마침 책의 내용에 시간에 대한 내용이 나오고 미래를 위해서 현재를 희생하는것이 현명한것인가에 대한 작가의 생각을 담고있다.
    안락함에 대한 이야기 사회 시스템에 대한 이야기 모두다 공감 할수 있는 이야기 하지만 하지만 난 어덯게 해야 한단 말인가?
    퇴사를 해도 된다는 말인가? 퇴사를 하면 어떻게 생활을 이어 나가야 한다는 말인가? 서른여섯 나이에 할 줄 아는것은 없고 사업도 할수 없이 그냥 퇴사를 해도 된다는것인가?
    퇴사 하고 싶다.일하기 싫어 그럼 무엇을 해야 하지?
    나는 무엇을 할 수 있지?
    그림도 못그리고 이야기도 쓰지 못해
    프로그램도 못 만들어
    무엇하나 재대로 할 수 있는 것이 없다.'
*** 지호의 짐승돌 컨샙
    아님들에서 지호가 남돌이 되면 해보고 싶은 컨샙을 이야기하면서 투피엠의 짐승돌컨샙을 해보고 싶다고 했다.
    하고 싶다면 했으면 좋겠다. 회사를 기고 해야만 한는것은 아니니까
    나서서 투피엠 커버 무대를 스스로 준비하고 공개를 할수 있을텐데 햇으면 좋겠다.
    그리고 무대의 마지막은 파격적으로 택연의 상의 찟는 퍼포먼스를 여자가 재연한다면 완전 간지 쩔지 않을가 싶은데..아마 안되겠지?...
*** 인천항 화재
    인천항에 화재가 발생했다. 자세한 내용은 알지 못하지만 그피해가 우리집까지 탄냄새가 전해졌다.
    당연히 유해한 가스를 포함했을건대 간만에 대기 상태가 좋았는데 아주 큰 빅 엿을 선물 받았다.
    대체 뭐땜에 화재가 발생했는지 보나마나 부주의겠지
    만오천톤급 선박에 발생한 화제로 리비아로 수출하기로한 중고차가 불에 타고 있다고
    선박 내부의 화재로 진화가 어렵다고 소방당국에서 말했다고
    불이 커질때가지 관리 책임자는 뭐한건가?
    인천 대기오염의 피해보상을 청구해야한다.
*** 유시아 정말 특별한
    반응 리액션이 정말 알수 없는 이상하기도 하고 재미있기도 하고 귀엽
*** 23:45
    이제 자야지 잠이 부족해 잠이 부족한 이유가 생산적이지 않으므로 잠을 자야지

** <2018-05-22 화> 오늘의 글
*** 페도라 28 버전 업데이트
    우선 패도라 28버전이 올라 왔기레 업데이트 하였다. 아직까지 눈에 띄는 변화는 느끼지 못했다.
    페도라는 정식으로 작업이나 학습에 사용하지 않았기에 느끼지 못하는것 일것이다.
    막연한 리눅스를 향한 동경이 있다. 정확히는 리눅스가 아니고 컴퓨터를 잘하는것 해커가 되는것에대한 동경이다.
    역시나 영어를 하지 못하면 길이 없다는것을 다식 확인하게 되었던...
*** 아침
    아침으로 동생이 편의점에서 왕뚜껑 김치맛과 게딱지 삼각김밥과 햄버거를 사와서 그자리에서 모두 먹어치웠다.
    아침부터 과식을 했더니 속이 별로 좋지 않다 뭔가 안에서 뜨거운 기운이 느껴진다.
    과식은 언제나 후회를 하지만 먹을때는 자제를 하지 못하겠다. 남은면 버려야 하기때문에
    편의점과 배달음식을 많이 이용하면서 양조절이 안되고 있다.
    분명한 문제를 인식하고 있다. 그리고 개선이 필요한 부분이다. 과식은 무척이나 위험하다 현재도 온몸으로 느끼고 있는중이다.
*** 스포티파이
    팟캐스트 디자인테이블을 들으면서 몇번언급이 나왔던 스포티파이를 검색을 통해서 음악 스트레밍 서비스라는것을알게 되었다.
    해외스트리밍서비스는 국내에 들어오지 못하고있다.
    서비스를 막아 놓아서 그런걸로 알고있는데 무엇때문일까? 누가 막고 있는것일까?

    내가 진리라고 믿는 누군가의 말이 있다
    인간은 유혹을 이길수 없다 유혹을 이기는 인간이 있다면 그것은 유혹이 약했기 때문일것이다.
    음악을 무료로 들을수 있다면 누가 돈을 지불하고 음악을 들을것인가?
    개다가 처벌 받을 가능성이 무척 낮다면 ?
    스포티 파이의 의견은 무척이나 설득력이 있다.
    음원을 불법으로 사용하는 사람들의경우 제작하는사람에게 지불되는 금액은 0이다
    하지만 사용자는 무료로 음악을 이용하지만 재작자에서 스포티파이는 매출의 70퍼샌트를 지불한다고 하니 0과 20억달라는 무척이나 논리적인 근거이다.
    하지만 여기서 다른 맹점이 존재한다. 기술이 발전한 시점이 온것이다
    스포니 파이의 주장이 맞는경우인것은 불법으로 음악을 공유하는것을 막을방도가 없었던 때에 해당하는 이야기이고 언젠가 불법공유를 완전히 막을 기술이 발견되는경우는 
    0 대 20억 달라는 전혀 틀린 주장이 될것이다.
    현재는 어쩔수 없는것이 있는거고 과도기라 생각한다.
    손실은 맞지만 더 큰 파이, 하지만 음악은 공짜라는 인식과 이익을 바꾸게 된느것은 좀 위험할 수 있다.
    
    현재 음익시장은 무척이나 이상한 모양을 하고 있다.
    음반이 여전히 발매돼고 있고 그음반은 대중을 타깃으로 하지 않고 있다. 일부 팬덤을 향하고 있다.
    대중가수라 할수 없다.
    어째서 더 큰 가능성을 보지 않고 작은 이익에만 아티스트를 소모하는지 어쩔수 없는것인지
    팬덤만보고 장사를 해도 회사를 운영할수있는것이 장기적으로 보면 전혀 아티스트를 그저 소모하고 있는것이 확실하다.
*** 황재숙 차장을 견디기 어려운 이유를 말해 본다.
**** 근무태만
     노닥거린다. 이사의 눈치를 보며 이사가 자리를 비우면 일을 하지 않는다.한가한경우엔 문재가 크지 않지만 정말 바쁠때 나는 죽어나고 있는데 그레버리면 정말 때려치고 싶은적이 한두번이 아니다.
     영동오산항공기 연로 시설 할때 황차장이 일을 재때 했다면 영동일이 이렇게 엉망이 되지는 안았고 그것때문에 연쇄적으로 모든일이 고이게 된 모든 원흉이다.
     무슨 질의서를 몇주동안 작성하고 이렉션을 한달동안 그린단 말인가?
     그것도 결과물을 보니 정말 말도 안되게 허접한 모양으로, 그동안 나에게 했던 말들이 모두 무색하게 스케일도 작고 글씨크기도 마무렇게나했으며 마크는 겹쳐저있고 빠진 마크도 있고
     보여져야할 것을 만들지 않은것도 있고 이따위로 해놓고 말로만 작업자를 위한다는 개소리나 해대고
     표현의 방법은 여러가지라는것을 전혀 이해 하지않고 자신이 했던 방법으로만 하려 하고 남의 의사를 무시해버린다.
     자신이 했던 방법이라함은 그냥 과거에 했던것 세상이 바뀐것에 전혀 무관하게 옛방법만을 고수하고 있다.
     본인만 그리하면 문제는 없다. 하지만 남에게 강요할때는 전혀 이야기가 다르다 이해를 시켜주어야 한다.
     왜 조인트 디태일에 볼트겟수를 일일히 써주어야 하는가? 몇번의 프로잭에 전혀 문재 없던것을 왜 본인만 그런단 말이냐구.
     문재 없다면 간편하고 수월한 방법이 좋다. 틀릴 일을 굳이 
     황차장이 재기한 문재는 거의다 아무런 문재없는 부분들이다. 
     아무도 보지 않는 도면을 만드는데 힘을 쏟을 일이 무었이냐는 말이다.
     아무도 보지 않는다는 말이다.
     조인트의 볼트겟수를 표기하건 안하건 
=======
    세로운 기술
<<<<<<< HEAD
*** 산타마리아춤 게임
    시장에 가면이란 게임을 응용한게임으로 하사람씩 동작을 추가해서 쌓아가는 게임
*** 아파트 게임
    참가자중 아무나 층수를 말하고 말하는순간 참가자의 손을 한데 모아 쌓는다 
    맨 아래부터 차례로 손을 빼서 맨위로 올리면서 카운트를 센다. 처음 말한 층수에 손을 올리는 참가자가 벌칙을 받는다.
*** 
=======
**** 게임위 만들어 보자
***** 도구 선택
      Unity
      양궁?
      
>>>>>>> 758ff5e0dda57ce281894f02f0ff503bfdb45b0f
>>>>>>> 1876becde8013583eab9d883f3fd5e16f0b75caf
