* 리뷰
** 식품
*** 농심 포스틱
    + 가격 ???
    + 시식 후기
      맛있음
      
      
** 가전
*** 샤오미 공기청정기S2    
    + 가격
      20만원
    + 사용기
      AUTO모드에서는 소음이 없음
      하지만 공기 청정 효과역시 거의 없다고 보임
      팬으로 공기를 흡입하고 필터로 걸러서 내보내는 선풍기에 필터를 달아 놓은듯한 구조
      옆에서 밥을 먹었는데 아무런 반응 없음-냄세 재거기능은 없는것 같은
** V App
*** 효정
**** 내용
     트와이스 콘서트 관람후 바로 잠을 자기 전에 연습실에와서 연습하던중 켠 노래연습겸 브이앱
     러블리즈, 보아, 여자친구, 현아...등등의 노래를 불렀다
     브이앱이라서 연습이라기보다 뽐내기가 괭어버렀지만 이런기회가 자주 있었으면 좋겠다.
**** 
=======
* 영어공부
  필요함을 절실하게 느끼면서도 엄두를 내지 못하고 있다.
  공부 또는 일을 하면서 언제나 정보의 갈증을 느끼는 지점에 항상 영어를 마주하게 된다.
  영어를 할줄 안다면 더 성장 할수 있었던 순간들 지금과는 다른 환경이 되어있을수 있었던 가능성의 순간들
  나는 기술과 정보를 원하고 그것들을 얻기 위해서 영어가 필요한것이다.
** 영어 공부계획
   말을 처음 배웠던 경험은 없다. 이미 내기억에선 말을 배운후이기 때문이다.
   아이들이 말을 배우는것을 보면 아이와 소통하기 위해서 아이를 둘러싼 모든것들이 협조를 하고 있다.
   아이의 입에서 아빠라는 말을 엄마라는 말을 듣기위해서 부모들은 열과 성을 다한다.
   지금의 나에서 그런 환경을 바랄 수는 없다.
   가장 걸림돌이 되는것은 나는 말이없다는것이다
   표현을 하지않는것이 습관화 돼어서 생각 자채를 하지 않아버린다.
   무언가 글을쓰고 싶지만 내 안에 생각이라는것이 감상이라는것이 떠오르지 않는다.
   예로 많은사람들은 무언가 주변의 환경에 감상을 가지고 표현을 하는것을 난는 보게 된다.
   하지만 똑같은 환경에서 나는 아무것도 느끼지 못하고 그래서 감상또한 없다.
   인터넷에 보면 저마다 맞건 틀리건 자기 자신을 표현하지 못해 안달난사람들이 가득해보인다.
   실시간 방송에 바로바로피드백을 달거나 게임을 하면서 수많은 이야기를 하는 사람들을보며 나도
   같이 어울리고 싶지만 아무런 생각이 없기때문에 끼어들수 없었다.
   게임을 공부했을때도 만드는 기술을 배우는 것보다 항상 만들것을 찾는일이 어려웠고 해내지 못한체
   시간을 다써버리고 멈추어 버린 일이 항상 일어 났다.
   나는 생각없이 수용하는 수용적인 태도를 가지고 산지가 너무나도 오랜세월이라서 
   이 시스템을 바꾸지 않는다면 영어든 무었이든 나는 앞으로 나갈수 없다고 생각한다.
   그래서 매일 만화그리기와 글쓰기를 하려고 했으나 잘 되지 않았다.
   이런 두서 없이 글쓰기가 도음이 되기를 바라지만 과연
   트래이닝 만으로 잘 되기를 바라고 있을 수 만은 없다 이미 나에게 주어진 시간의 상당부분을 
   소비 하였기 때문에 또 얼마나 시간이 남아있는지 알 수 없으므로 하루하루를 귀하게 사용해야 한다.
   그러기 위해서 내가 해야할 일들을 생각나는데로 적어 본다.
*** 계획하기
    남은 시간동안 더 나은 삶을위해서 해야할 일을 적어본다.
**** 글쓰기
     감상이든 리뷰든 아무말이든 글로써 생각을 정리하고 될수있다면 타인에서 전달할수 있도록 해본다.    
     가장 쉬운면서 가장 어련운 일이라고 생각이된다.
     나의 생각을 가지고 정리해서 이제는 밖으로 분출을 할수 있도록 한다.
     - 리뷰
     - 감상문
**** 만화그리기
     이야기와 연출이 담겨있는 그림을 그리고 완성을 할수있도록 한다.
     - 4컷
     - 1컷
     - 서사       
**** 게임 만들기
     글과 만화의 최종 아웃풋은 게임이어야 한다.
     - cpp
     - c#
     - lisp
**** 영어
     글쓰기를 하건 만화를 그리건 게임을 만들건 더 넓은 세계로 나가기위한 최고의 도구, 기술, 지침서라고 생각한다.
*** 기술에 현혹되지 말자
    그동한 공부할때 시행착오를 격은것중 하나인데 기술에 너무 현혹 되는 경우가 많았다.
    세로운 기술
*** 산타마리아춤 게임
    시장에 가면이란 게임을 응용한게임으로 하사람씩 동작을 추가해서 쌓아가는 게임
*** 아파트 게임
    참가자중 아무나 층수를 말하고 말하는순간 참가자의 손을 한데 모아 쌓는다 
    맨 아래부터 차례로 손을 빼서 맨위로 올리면서 카운트를 센다. 처음 말한 층수에 손을 올리는 참가자가 벌칙을 받는다.
*** 
